extends:
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: "tsconfig.json"
plugins:
  - react
  - "@typescript-eslint"
rules:
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-unused-vars': off
